spring.application.name=ACTIVITY-SERVICE
server.port=8082

#connection with the mongoDB
spring.data.mongodb.uri=mongodb+srv://mbenash961030_db_user:kG1EWf0KhYBO604S@cluster0.mpzwtt4.mongodb.net/fitness_tracker?appName=Cluster0

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
rabbitmq.exchange.name=activity.exchange
rabbitmq.routing.key=activity.routing.key


#connection with the eureka service
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/