spring.application.name=activity-service
server.port=8082

#connection with the mongoDB
spring.mongodb.uri=mongodb+srv://mbenash961030_db_user:kG1EWf0KhYBO604S@cluster0.mpzwtt4.mongodb.net/fitness_tracker?appName=Cluster0


#connection with the eureka service
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/