spring.application.name=api-gateway

# client connection with the config server
spring.config.import=optional:configserver:http://localhost:8888

# local fallback routes (used if config server is unavailable)
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.server.webflux.routes[1].id=ai-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://AI-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/ai/**
spring.cloud.gateway.server.webflux.routes[2].id=activity-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://ACTIVITY-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/activities/**

# local fallback eureka endpoint
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# local fallback for resource-server JWT decoder (overridden by config server if provided)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/fitness-oAuth2/protocol/openid-connect/certs
