spring.application.name=api-gateway

# client connection with the config server
spring.config.import=optional:configserver:http://localhost:8888

# local fallback for resource-server JWT decoder (overridden by config server if provided)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/fitness-oAuth2/protocol/openid-connect/certs

