spring.application.name=ai-service
server.port=8083

#client connection with the config server
spring.config.import=optional:configserver:http://localhost:8888

# Local fallbacks used when Config Server is unavailable
rabbitmq.queue.name=activity.queue
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1/models/gemini-1.5-flash:generateContent}
gemini.api.key=AIzaSyAsOjDX5e1ufrmYOPb3XnxlNsQekx7KoAI
