spring.application.name=ai-service
server.port=8083

#connection with the mongoDB
spring.mongodb.uri=mongodb+srv://mbenash961030_db_user:kG1EWf0KhYBO604S@cluster0.mpzwtt4.mongodb.net/fitness_tracker?appName=Cluster0

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
rabbitmq.exchange.name=activity.exchange
rabbitmq.routing.key=activity.routing.key
rabbitmq.queue.name=activity.queue


#Gemini Ai connection
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent}
gemini.api.key=${GEMINI_API_KEY:}

#connection with the eureka service
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Eureka instance networking (avoid .mshome.net DNS resolution failures)
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
