spring.application.name=api-gateway

# Enable discovery for Gateway
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route 0: User Service
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**

# Route 1: AI Service
spring.cloud.gateway.routes[1].id=ai-service
spring.cloud.gateway.routes[1].uri=lb://ai-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/ai/**

# Route 2: Activity Service
spring.cloud.gateway.routes[2].id=activity-service
spring.cloud.gateway.routes[2].uri=lb://activity-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/activities/**

server.port=8080

# Eureka connection
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# oauth configuration
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8181/realms/fitness-oAuth2/protocol/openid-connect/certs
