spring.application.name=config-Server
server.port=8888

#tell the spring cloud to look for local/native configurations instead of git
#second one tell the class path it needs to look for that config
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/Config

