# Application name
spring.application.name=user-service

#client connection with the config server
spring.config.import=optional:configserver:http://localhost:8888

# Local fallback to keep entity changes in sync when config server is down
spring.jpa.hibernate.ddl-auto=update

