spring.application.name=userservice
spring.datasource.url=jdbc:postgresql://ep-gentle-paper-am7ngaee-pooler.c-5.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_XJSkbfy3Ur5o&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_XJSkbfy3Ur5o
server.port=8081